---
title: "Rworksheet_Canonicato#4a"
author: "Dianah Marie Canonicato"
date: "2023-10-25"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r name, echo=TRUE }

#Worksheet-4a in R

#1. The table below shows the data about shoe size and height. Create a data frame.




Household_Data<- data.frame(Shoesize = c(6.5, 9.0, 8.5, 8.5, 10.5,7.0, 9.5, 9.0, 13.0, 7.5, 10.5, 8.5, 12.0,10.5,13.0, 11.5, 8.5, 5.0, 10.0, 6.5, 7.5,8.5,10.5, 8.5, 10.5, 11.0,9.0,13.0),
                 Height = c(66.0, 68.0, 64.5, 65.0, 70.0, 64.0, 70.0, 71.0, 72.0, 64.0, 74.5, 67.0, 71.0, 71.0, 77.0, 72.0, 59.0, 62.0, 72.0, 66.0, 64.0, 67.0, 73.0, 69.00, 72.0, 70.0, 69.0, 70.0),
                 Gender = c('F','F','F','F','M','F','F','F', 'M','F','M','F','M','M', 'M','M','F','F','M','F', 'F','M', 'M','F','M','M','M','M')
                 
)
Household_Data


#a. Describe the data.

#Household_Data  is a data frame containing 27 observations of three variables: Shoe size, Height, and Gender. Shoesize is a continuous numeric variable with a range of values between 5.0 and 13.0, representing the size of the participants' shoes. Height is a continuous numeric variable with a range of values between 59.0 and 77.0, representing the height of the participants. Gender is a categorical variable with two levels: 'F' and 'M', representing the gender of the participants.

#b. Create a subset by males and females with their corresponding shoe size and height. What its result? Show the R scripts.

Males <- subset (Household_Data, Gender =="M" )
Females <- subset (Household_Data, Gender =="F")

Males
Females

#c. Find the mean of shoe size and height of the respondents. Write the R scripts and its result.

# Calculate the mean shoe size and height of the respondents
mean_shoe_size <- mean(Household_Data$Shoesize)

mean_height <- mean(Household_Data$Height)

cat("The mean shoe size of the respondents is:", mean_shoe_size, "\n")
cat("The mean height of the respondents is:", mean_height, "\n")

#d. Is there a relationship between shoe size and height? Why?
#There is no apparent relationship between shoe size and height in this dataset. This can be seen from the descriptive statistics where the mean shoe size is approximately 9.2, and the mean height is approximately 68.3. Although there is a small difference in height and shoe size (approximately 1 inch), it is not significant enough to suggest a correlation between the two variables.

#2. Construct character vector months to a factor with factor() and assign the result to factor_months_vector. Print out factor_months_vector and assert that R prints out the factor levels below the actual values.

months_vector <- c("March","April","January","November","January",
                          "September","October","September","November","August",
                          "January","November","November","February","May","August","July","December","August","August","September","November","February",
                          "April")
factor_months_vector<-  factor (months_vector)
factor_months_vector


#3. Then check the summary() of the months_vector and factor_months_vector. | Inter-pret the results of both vectors. Are they both equally useful in this case?

summary(months_vector)
summary (factor_months_vector)


#Interpretation: Both vectors are useful in their own right, but the factor vector allows R to treat the data categorically and provide additional information about the frequency and distribution of each category.

#4. Create a vector and factor for the table below.

factor_data <- rep (c("East", "West", "North"), c(1,4,3))

new_order_data <- factor(factor_data, levels = c("East","West", "North"))
print(new_order_data)







```

